### ISSUE TITLE
Update site sending br encoded xml files (Brotli)

### ISSUE THREAD

**Issue by ceford** [joomla/update.joomla.org#338] opened 2023-10-30 16:54 UTC
This seems recent and intermittent! I have a number of production J4 sites and several localhost test sites recently updated to J4.4. I have some local J4.3 test sites that I can't update and a new local J4.4 site for which I can't reinstall core files. To figure what is going on I set $options[CURLOPT_VERBOSE] = true; on line 164 of libraries/src/Http/Transport/CurlTransport.php and used the cli command php j44/cli/joomla.php update:extensions:check to see the headers and responses (separately on both local and remote sites),

The local site has this in the response for the first file fetched, core/list.xml:
```
< last-modified: Wed, 18 Oct 2023 07:30:24 GMT
< content-encoding: br
< vary: Accept-Encoding
```
And when we get to line 228 of libraries/src/Updater/Adapter/CollectionAdapter.php i can see that $response->body contains binary data. I have saved that data and used a command line utility to verify that it is indeed the br encoded version of the xml file requested. So the xml_parse function fails. 

The second xml file fetched, language/translationlist_4.xml, is not br encoded so does not cause an error.

I hope someone can look at what is going on in the update server.

**Comment by zero-24** [comment] 2023-10-30 17:21
could you try it against update1.joomla.org/... and see whether the same issue can be reproduced there?

**Comment by ceford** [comment] 2023-10-30 18:33
After changing the update site with phpMyAdmin the cli works and I can see there is no br encoding (with repeated calls). However, In Joomla admin when I use the  System / Update Joomla / Check for Updates button the source is reset to update.joomla.org and I get the error message: Update: :Collection: Could not parse https://update.joomla.org/core/list.xml.

**Comment by HLeithner** [comment] 2023-10-30 18:37
I disabled brotli now on cloudflare, can you test again please?

**Comment by ceford** [comment] 2023-10-30 19:25
With the update1.joomla.org domain the cli now works without error. I can see the downloads are not br encoded. The normal admin interface changes the domain back to update.joomla.org - so the error is back.

**Comment by robertcolinnewell** [comment] 2023-10-30 20:36
Thank you for the concise and technical explanation -- I have been seeing these errors on all my Joomla 4 and 5 sites...
And there wasn't much of an explanation over at Joomla Forums...

Errors include.

Update: :Collection: Could not parse https://update.joomla.org/core/list.xml
Update: :Extension: Could not parse https://update.joomla.org/core/extensions/com_joomlaupdate.xml

**Comment by HLeithner** [comment] 2023-10-30 21:09
Can someone please send me a superuser access to one affected site (test installation would be good) to harald.leithner@community.joomla.org thanks

**Comment by ceford** [comment] 2023-10-30 22:57
> Can someone please send me a superuser access to one affected site (test installation would be good) to [harald.leithner@community.joomla.org](mailto:harald.leithner@community.joomla.org) thanks

Neither of the VPS systems I use show the error. It only occurs on my home computers, a Mac with the same error on Firefox, Chrome and Safari, and a Linux box using Firefox: `Update: :Collection: Could not parse https://update.joomla.org/core/list.xml` - so I can't offer a test site (and will be away tomorrow for a couple of days).

**Comment by sozzled** [comment] 2023-10-30 23:06
> I have been seeing these errors on all my Joomla 4 and 5 sites... And there wasn't much of an explanation over at Joomla Forums...

I see these same errors on all my J! 3._x_, 4._x_ and 5.0 websites.  Used several devices and browsers; commercially-hosted and PC-hosted (Wampserver) websites:  all the same.

> Update: :Collection: Could not parse https://update.joomla.org/core/list.xml Update: :Extension: Could not parse https://update.joomla.org/core/extensions/com_joomlaupdate.xml

There is no explanation at The Joomla Forum™—the problem seems to be dismissed as something intermittent—and I'm surprised there's been no mention on Mattermost.  See also comments at https://forum.joomla.org/viewtopic.php?f=812&t=1005048

**Comment by robertcolinnewell** [comment] 2023-10-30 23:12
It's a pity that, within the Joomla admin. interface, that one cannot edit the URL of the update sites --

As one URL is working and the other is not.

**Comment by HLeithner** [comment] 2023-10-31 07:27
@ceford can you try again please?

**Comment by ceford** [comment] 2023-10-31 09:33
With the normal update sites (update.joomla.org) I now see no cli errors and the atum System / Update / Joomla works normally - I just reinstalled Joomla Core Files on my localhost test installation. All good!

**Comment by HLeithner** [comment] 2023-10-31 10:46
thanks, then I'm closing this.

**Closed by HLeithner** 2023-10-31 10:46 UTC
